services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=Primary
      - POSTGRES_PASSWORD=Punkhazard4!
      - POSTGRES_USER=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen para persistencia de datos
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '7070:7070'
    depends_on:
      - postgres

volumes:
  postgres_data:  # Definición del volumen persistente
