name: Deploy to server

on:
  push:
    branches:
      - main  # O la rama que deseas que dispare la acción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./"
          target: "/home/ubuntu/GeekBank"

      - name: Run deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /ruta/del/proyecto/en/el/servidor
            git pull origin main  # O la rama que estés usando
            ./deploy.sh  # Este puede ser un script personalizado para reiniciar servicios o aplicaciones
